#!/bin/bash

# Copyright 2018 Timothy Baldwin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e -o pipefail
cd "$(dirname "$0")"
unset $(compgen -v GIT)
mkdir -p git split cvsroot/CVSROOT

bwrap=(bwrap --unsetenv TMPDIR --cap-drop ALL --die-with-parent --unshare-all --proc /proc --dev /dev --dir /tmp )

make -f sandbox.mk

for i in /etc/alternatives /usr /bin /sbin /lib*
do
  if [[ -L $i ]]; then
    bwrap+=(--symlink "$(readlink "$i")" "$i")
  else
    bwrap+=(--ro-bind "$i" "$i")
  fi
done

"${bwrap[@]}" --bind cvs-fast-export /s --tmpfs /s/.git make -j$(getconf _NPROCESSORS_ONLN) -C /s -k cvs-fast-export

prepare_git() {
  mkdir -p "$1"
  cd "$1"
  ! rm -rf .git
  git init .
  echo "ref: refs/heads/$2_master" > .git/HEAD
}

convert() {
  set -e -o pipefail
  echo Processing ${1}...
  prefix="${1//\//_}"
  exec >"/split/${prefix}_log"
  exec 2>&1
  echo
  echo Processing ${1}...
  if [[ -v split ]]; then
    prepare_git "/split/${prefix}" "${prefix}"
  fi
  dir="/home/rool/rab/cvsroot"
  find "$dir/$1" -type f | \
  /cfe --strip "$dir/$1" --commit-time-window 600 --tag-prefix "refs/original/tags/${prefix}_" --branch-prefix "refs/original/heads/${prefix}_"  --verbose | \
  git fast-import
  if [[ -v split ]]; then
    python3 /fixup.py
  fi
  echo ${1} Processed
}



process() {

  if [[ ! -v split ]]; then
    prepare_git git apache_RiscOS_Sources_Kernel
  fi

  (
    cd /home/rool/rab/cvsroot
    perl -ne '/^([a-zA-Z]+[^\s]*)\s/; $_ = $1; tr:.:/:; print "$_\n" if -d $_;' Products/*/modules,v
    printf "%s\n" Products/*
  ) | sort -u | parallel convert

  if [[ ! -v split ]]; then
    python3 /fixup.py
  fi

}

export -f convert prepare_git process

"${bwrap[@]}"  --seccomp 9 9<seccomp --bind cvsroot/CVSROOT /c/CVSROOT cvs -d /c init

"${bwrap[@]}"  --seccomp 9 9<seccomp --ro-bind cvsroot /home/rool/rab/cvsroot --bind git /git --bind split /split --ro-bind fixup.py /fixup.py --ro-bind cvs-fast-export/cvs-fast-export /cfe --chdir / bash -c process
